name: CI/CD with python and flask

on:
  push:
    branches:
      - main
      - Ricardo

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: 🔐 Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🏗️ Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/ricardoastudillo05/ricardo:latest

    - name: 🧾 Mostrar variables básicas (solo locales, no secretos)
      run: |
        echo "Probando conexión SSH con:"
        echo "Host: ${{ secrets.VPS_HOST }}"
        echo "Usuario: ${{ secrets.VPS_USER }}"
        echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"
    
    - name: 🧪 Probar conexión SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "✅ Conexión exitosa desde GitHub Actions"
          hostname
          whoami
          uptime
          
    - name: Copiar stack.yml to VPS (SCP)
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        source: "stack.yml"
        target: "/home/${{ secrets.VPS_USER }}/deploy1"

    - name: Despliegue de servicios
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "✅ Desplegando servicios"
          cd ~/deploy1

          echo "Descargando la imagen desde GIT"
          echo "${{ secrets.VPS_GHCR_PATH }}" | docker login ghcr.io -u ricardoastudillo05 --password-stdin
          docker pull ghcr.io/ricardoastudillo05/ricardo:latest
  

